# Generated by Django 4.0.5 on 2022-06-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listings_com_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='com',
            name='onlist',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='type',
        ),
        migrations.DeleteModel(
            name='bid',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='com',
        ),
        migrations.DeleteModel(
            name='listings',
        ),
    ]
