# Generated by Django 4.0.5 on 2022-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_date_alter_com_date_alter_listings_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='minp',
        ),
        migrations.AddField(
            model_name='listings',
            name='minp',
            field=models.IntegerField(null=True),
        ),
    ]
