# Generated by Django 4.0.5 on 2022-06-25 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_maxp'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.ImageField(default='', upload_to='auction/images'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.listings'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='maxp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='minp',
            field=models.IntegerField(),
        ),
    ]
