# Generated by Django 4.0.5 on 2022-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listings_image_alter_bid_item_alter_bid_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='minp',
            field=models.IntegerField(default=0),
        ),
    ]
