# Generated by Django 4.0.5 on 2022-06-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listings_image_listings_listimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='listimage',
            field=models.ImageField(default='', upload_to='auction/images/'),
        ),
    ]
