# Generated by Django 4.0.5 on 2022-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listings_listimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='listimage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
