# Generated by Django 4.0.5 on 2022-07-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_listings_listimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='win',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=60)),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctions.listings')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid')),
            ],
        ),
    ]
